### ISSUE TITLE
Cannot find database.sqlite with docker-compose deployment

### ISSUE THREAD

**Issue by reverie89** [usetrmnl/byos_laravel#51]
Hi, I am using  the [docker-compose.yml](https://github.com/usetrmnl/byos_laravel/blob/main/docker/prod/docker-compose.yml) file as follows:
```
services:
    app:
        image: ghcr.io/usetrmnl/byos_laravel:latest
        ports:
            - "4567:8080"
        environment:
            - REGISTRATION_ENABLED=0
            #- APP_KEY=
            - PHP_OPCACHE_ENABLE=1
            - TRMNL_PROXY_REFRESH_MINUTES=15
            - DB_DATABASE=database/storage/database.sqlite
        volumes:
            - database:/var/www/html/database/storage
            - storage:/var/www/html/storage/app/public/images/generated
        restart: unless-stopped
volumes:
    database:
    storage:
```

Running `docker logs -f app` shows:
```
In Connection.php line 822:

  Database file at path [database/storage/database.sqlite] does not exist. En
  sure this is an absolute path to the database. (Connection: sqlite, SQL: se
  lect exists (select 1 from "main".sqlite_master where name = 'migrations' a
  nd type = 'table') as "exists")


In SQLiteConnector.php line 59:

  Database file at path [database/storage/database.sqlite] does not exist. En
  sure this is an absolute path to the database.
```

I don't think the path `database/storage/database.sqlite` is correct, but changing the env variable to `/var/www/html/database/storage` doesn't work either:

```
Connection.php line 822:

  Database file at path [/var/www/html/database/storage/database.sqlite] does
   not exist. Ensure this is an absolute path to the database. (Connection: s
  qlite, SQL: select exists (select 1 from "main".sqlite_master where name =
  'migrations' and type = 'table') as "exists")


In SQLiteConnector.php line 59:

  Database file at path [/var/www/html/database/storage/database.sqlite] does
   not exist. Ensure this is an absolute path to the database.
```

Where can I get a copy of the `database.sqlite` file or how do I generate it? The container keeps restarting because of this error so I can't enter into shell to use artisan...
